### ISSUE TITLE
Ubuntu 14.04/Uno R3 NoClassDefFoundError: gnu/io/PortInUseException

### ISSUE THREAD

**Issue by Cookiez-** [SINTEF-9012/JArduino#36]
Hi, I am trying to incorporate JArduino into Eclipse on Ubuntu 14.04. I have successfully compiled and uploaded JArduino firmware onto my board. However upload running the Blink.java example I get this run-time error:
Exception in thread "main" java.lang.NoClassDefFoundError: gnu/io/PortInUseException
	at Blink.main(Blink.java:42)
Caused by: java.lang.ClassNotFoundException: gnu.io.PortInUseException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
I have confirmed my board working using the native Arduino IDE. I have heard issues about Ubuntu 14.04 with the RXTX libraries of new port mappings and what not. Does anyone know to to fix the ports for JArduino? I have been stuck on this issue for several days now. Thank you

**Comment by jsutaria** [comment]
A. Make sure you are using the correct port, as this is quite important. The method I use to see what port my Arduino is on is to open the IDE and select your board and use that.
B. Try unplugging the board, then replugging it in.
C. Attempt to re install the firmware, then quit the Arduino IDE, and attempt to use the GUI provided by Jarduino.
